### ISSUE TITLE
Feature: Add Application layer on backend

### ISSUE THREAD

**Issue by hocinehacherouf** [CGI-FR/IoT-Hub-Portal#1256]
**Describe the solution you'd like**

- The Application layer should reference only `Domain/Shared` layers
- The Application layer defines interfaces that are implemented by outside layers: For example the interface `IDeviceService` should be on Application layer and its implementation must be on Infrastructure layer
- The Application layer defines mapping between entities and dtos

**Comment by kbeaugrand** [comment]
Need to define multiple tasks: 

- Add application Layer to the solution
- Migrate all mapper profiles to application layer
- Migrate services to application and infrastructure layer
   - ConfigService should be split (by devices and edgeDevices services) + use External device service instead of ``RegistryManager`` 
   - Devices/DeviceModels/DeviceTags/DeviceModelProperties/DeviceProperties/ConfigService => all in one service (DeviceManagementService), **keep in mind that there is a baseService to manage devices**
   - EdgeDevices/EdgeModels/ConfigService => all in one service (EdgeDeviceManagementService)
   - LoRaWANCommand/LoRaWanConcentrator/LoRaWanDevices -> all in one service ``LoRaWanManagementService``
   - IdeaService
   - ExternalDeviceService -> Should be renamed to ``AzureDeviceRegistryProvider`` in providers namespaces
- Migrate Wrappers (and integrate to the existing services)
- Migrate all managers
  - DeviceModelImageManager
  - DeviceProvisioningServiceManager -> Merged to ``AzureDeviceRegistryProvider`` 
  - RouterConfigManager/LoRaWanDeviceMethodManager  -> Migrate to ``LoRaWanManagementService``
  - ExportDeviceManager -> Migrate to ``ExportDeviceService``
- Migrate Resources & RouterConfigFiles
- Migrate Jobs to infrastructure
- Migrate Helpers to Application Layer
- Migrate Service HeathCheck to Infrastructure Layer
