### ISSUE TITLE
Bug: Post a device model with an empty model id

### ISSUE THREAD

**Issue by adcoly** [CGI-FR/IoT-Hub-Portal#277]
I tried to post a new device model through the API and I can't access to the device model detail :
![image](https://user-images.githubusercontent.com/33126264/154692370-25c84a57-6454-4323-b346-d4538c362320.png)

Here is the script I used to post this device model : 
![image](https://user-images.githubusercontent.com/33126264/154692692-0cf91495-aec2-42af-8919-429cfcbc60a3.png)

**Comment by adcoly** [comment]
I also tried to delete this device model and an error occured :
![image](https://user-images.githubusercontent.com/33126264/154693854-fa978c35-fa1b-499a-940f-1580b06114eb.png)

**Comment by kbeaugrand** [comment]
Hi @adcoly , 

Thank you for this issue submission. 
I'm working on it. 

The correction will be to check if the device model identifier is null or empty before creating it (otherwise, it will create a GUID model identifier).

As a workaround, you might be able to ether: 
- Post a device model omitting the model identifier inside the payload 
- Post a device model with your custom device model identifier
