### ISSUE TITLE
Bug: Can't access to a device out of the 1st page

### ISSUE THREAD

**Issue by adcoly** [CGI-FR/IoT-Hub-Portal#601]
## Expected Behavior
I click on the button to access to the 2nd page of the device list and I should see the devices listed in there.

## Current Behavior
The blue loading bar load endlessly and I can't access to my 11th sensor.

## Context (Environment)

**Portal version**: 1.0.8.50
**LoRaWAN Stack version**: 2.0.0

## Logs
![image](https://user-images.githubusercontent.com/33126264/163576427-a9058baa-3c9c-4b7f-a7b5-77b351a36ddb.png)

**Comment by hocinehacherouf** [comment]
The next page uri  (returned by api) is always null, due to the call to `Url.RouteUrl()`:
https://github.com/CGI-FR/IoT-Hub-Portal/blob/e8bff4ac7b255c792ff6367f6a54d588e5830d40/src/AzureIoTHub.Portal/Server/Controllers/v1.0/DevicesControllerBase.cs#L92-L103

This issue is simillar to dotnet/aspnetcore#14877

A workaround solution is to return directly the continuation token as a replacement of the generated uri.
